### ISSUE TITLE
Incorrect count when characters from basic character set extension are used

### ISSUE THREAD

**Issue by shdiwan** [matteogatti/sms-counter#2]
Characters from basic character set extension use up 2 characters and the same should be reflected in length.  
Even though the logic is present in code, this is happening because the chars function in countGsm7bitEx is not getting invoked.

**Comment by lowwa132** [comment]
Unfortunately this project does not seem to be maintained

**Comment by lowwa132** [comment]
@matteogatti please approve and merge this PR https://github.com/matteogatti/sms-counter/pull/12

**Comment by matteogatti** [comment]
Approved and merged @lowwa132 and @shdiwan
